Fix release stage of ci
Error was:
```
Error: [Cabal-7160]
The package list for 'hackage.haskell.org' does not exist. Run 'cabal update' to download it.

Error: Process completed with exit code 1.
```